_BASE_: ../Base-MGN.yml

MODEL:
  META_ARCHITECTURE: MoCo

  BACKBONE:
    WITH_IBN: True

  LOSSES:
    NAME: ("CrossEntropyLoss", "Cosface",)
    COSFACE:
      MARGIN: 0.25
      GAMMA: 32
      SCALE: 1.

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/mgn_R50-ibn_cos_moco
