_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_swin_backbone
    NORM: BN
    DEPTH: swin_tiny_patch4_window7_224
    FEAT_DIM: 768
    PRETRAIN: True

  HEADS:
    NORM: BN

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss", )

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [ 384, 128 ]
  SIZE_TEST: [ 384, 128 ]

SOLVER:
  BASE_LR: 0.00035
  ETA_MIN_LR: 0.0000007

OUTPUT_DIR: logs/market1501/sbs_swin_tiny
